#![allow(unused)]
use qu_ir::IrModule;

use std::{io::Write, process::Command};

mod cgenerator;
mod type_writer;

pub struct BackendGenerator;

pub enum TargetKind {
    Executable,
    Ccode,
}

impl BackendGenerator {
    pub fn new() -> Self {
        Self {}
    }

    pub fn generate_module(module: &IrModule, kind: TargetKind, output: String) -> Result<(), std::io::Error> {
        let code = cgenerator::Cgenerator::generate(module);
        match kind {
            TargetKind::Ccode => {
                let mut file = std::fs::File::options()
                    .truncate(true)
                    .create(true)
                    .write(true)
                    .open(output)?;
                write!(file, "// Generated by Qu Compiler\n\n{}", code);
            }
            TargetKind::Executable => {
                {
                    let mut file = std::fs::File::options()
                        .truncate(true)
                        .create_new(true)
                        .write(true)
                        .open(".qu-gen.c")?;
                    write!(file, "{}", code);
                }
                let status = Command::new("clang")
                    .arg("-w")
                    .arg("-o")
                    .arg(output)
                    .arg("-O3")
                    .arg("-std=c23")
                    .arg(".qu-gen.c")
                    .status()?;
                if !status.success() {
                    std::fs::remove_file(".qu-gen.c");
                    return Err(std::io::Error::new(std::io::ErrorKind::Other, format!("(qu-compiler:fatal): Clang backend failed")));
                }
                std::fs::remove_file(".qu-gen.c");
            },
        }
        Ok(())
    }
}
